-- =====================================================================
-- Real phone notifications (Web Push), no app store, no Telegram needed.
--   * The browser subscribes -> push_subscribe() stores the endpoint.
--   * Events (new offer, accepted, on the way, done, cancelled,
--     verification) -> private.push_send() -> pg_net -> Edge Function
--     `send-push` (VAPID signing + payload encryption) -> the phone.
--   * VAPID keys are generated by the Edge Function on first use and kept in
--     private.settings; the private key never leaves the server.
-- Telegram keeps working alongside. Idempotent: safe to run more than once.
-- =====================================================================

create table if not exists public.push_subscriptions (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references public.users (id) on delete cascade,
  endpoint     text not null unique,
  p256dh       text not null,
  auth         text not null,
  user_agent   text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index if not exists push_subscriptions_user_idx on public.push_subscriptions (user_id);
alter table public.push_subscriptions enable row level security;
-- No policies: only the SECURITY DEFINER functions below (and the Edge Function
-- with the service role, to drop expired endpoints) touch this table.
revoke all on public.push_subscriptions from anon, authenticated;
grant select, delete on public.push_subscriptions to service_role;

-- Shared secret between the database and the Edge Function.
insert into private.settings (key, value)
values ('push_secret', replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', ''))
on conflict (key) do nothing;
-- Where the Edge Function lives (this project's API URL; change it if you
-- run this file on another Supabase project).
insert into private.settings (key, value)
values ('supabase_url', 'https://taldbggqtkukiuzpjydg.supabase.co')
on conflict (key) do nothing;

-- ---------------------------------------------------------------------
-- Browser-facing RPCs
-- ---------------------------------------------------------------------
create or replace function public.push_subscribe(
  p_endpoint text, p_p256dh text, p_auth text, p_user_agent text default null
) returns void
language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is null then
    raise exception 'not_allowed' using errcode = '42501';
  end if;
  if p_endpoint !~ '^https://' or length(p_endpoint) > 1000
     or coalesce(length(p_p256dh), 0) not between 20 and 200
     or coalesce(length(p_auth), 0) not between 10 and 100 then
    raise exception 'invalid_subscription';
  end if;
  -- one device = one endpoint; it follows whoever is signed in on it
  insert into public.push_subscriptions (user_id, endpoint, p256dh, auth, user_agent)
  values (auth.uid(), p_endpoint, p_p256dh, p_auth, left(p_user_agent, 300))
  on conflict (endpoint) do update
    set user_id = excluded.user_id, p256dh = excluded.p256dh, auth = excluded.auth,
        user_agent = excluded.user_agent, updated_at = now();
end $$;

create or replace function public.push_unsubscribe(p_endpoint text) returns void
language sql security definer set search_path = public as $$
  delete from public.push_subscriptions where endpoint = p_endpoint and user_id = auth.uid();
$$;

create or replace function public.push_status() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.push_subscriptions where user_id = auth.uid());
$$;

create or replace function public.push_public_key() returns text
language sql stable security definer set search_path = public, private as $$
  select private.setting('vapid_public_key');
$$;

-- ---------------------------------------------------------------------
-- Edge Function (service role only)
-- ---------------------------------------------------------------------
create or replace function public.push_service_config() returns jsonb
language sql stable security definer set search_path = public, private as $$
  select jsonb_build_object(
    'public_key', private.setting('vapid_public_key'),
    'private_key', private.setting('vapid_private_key'),
    'secret', private.setting('push_secret'),
    'app_url', private.setting('app_url'));
$$;

create or replace function public.push_service_init(p_public text, p_private text) returns text
language plpgsql security definer set search_path = public, private as $$
begin
  -- first writer wins; later calls keep the existing pair
  insert into private.settings (key, value) values ('vapid_public_key', p_public) on conflict (key) do nothing;
  insert into private.settings (key, value) values ('vapid_private_key', p_private) on conflict (key) do nothing;
  return private.setting('vapid_public_key');
end $$;

-- ---------------------------------------------------------------------
-- Sending
-- ---------------------------------------------------------------------
create or replace function private.push_send(
  p_user_id uuid, p_title text, p_body text, p_url text default '/', p_tag text default null
) returns void
language plpgsql security definer set search_path = public, private as $$
declare
  v_base text := private.setting('supabase_url');
  v_secret text := private.setting('push_secret');
  v_subs jsonb;
begin
  if v_base is null or v_secret is null or p_user_id is null then
    return;
  end if;
  select jsonb_agg(jsonb_build_object('endpoint', endpoint, 'p256dh', p256dh, 'auth', auth))
    into v_subs
  from public.push_subscriptions where user_id = p_user_id;
  if v_subs is null then
    return;
  end if;
  perform net.http_post(
    url := rtrim(v_base, '/') || '/functions/v1/send-push',
    body := jsonb_build_object('action', 'send', 'title', p_title, 'body', p_body,
                               'url', coalesce(p_url, '/'), 'tag', p_tag, 'subscriptions', v_subs),
    headers := jsonb_build_object('Content-Type', 'application/json', 'x-push-secret', v_secret)
  );
exception when others then
  raise warning 'push_send failed: %', sqlerrm;
end $$;

-- new offer -> provider
create or replace function public.push_new_offer() returns trigger
language plpgsql security definer set search_path = public, private as $$
declare r record;
begin
  if new.status <> 'offered' or (tg_op = 'UPDATE' and old.status = 'offered') then
    return new;
  end if;
  select s.name_ar, sr.problem_type, sr.area,
         case sr.time_slot when 'now' then 'هسه (مستعجل)' when 'today' then 'اليوم'
                           when 'tomorrow' then 'باچر' else 'موعد محدد' end as slot
    into r
  from public.service_requests sr join public.services s on s.id = sr.service_id
  where sr.id = new.request_id;
  perform private.push_send(new.provider_id,
    '🔔 طلب جديد إلك: ' || r.name_ar,
    r.problem_type || ' · ' || r.area || ' · ' || r.slot || chr(10) || 'أول فني يقبل ياخذ الطلب',
    '/requests/' || new.request_id, 'offer-' || new.request_id);
  return new;
exception when others then
  raise warning 'push_new_offer failed: %', sqlerrm;
  return new;
end $$;

drop trigger if exists provider_requests_push on public.provider_requests;
create trigger provider_requests_push
  after insert or update of status on public.provider_requests
  for each row execute function public.push_new_offer();

-- request status -> customer (and the provider when the customer cancels)
create or replace function public.push_request_status() returns trigger
language plpgsql security definer set search_path = public, private as $$
declare
  v_name text;
  v_url text := '/requests/' || new.id;
  v_tag text := 'req-' || new.id;
begin
  if new.status = old.status then
    return new;
  end if;
  select split_part(display_name, ' ', 1) into v_name from public.providers where id = new.provider_id;
  v_name := coalesce(v_name, 'الفني');

  case new.status
    when 'ACCEPTED' then
      perform private.push_send(new.customer_id, '✅ ' || v_name || ' قبل طلبك',
        'هسه تگدر تتصل بيه، وراح نبلغك من يطلع بالطريق.', v_url, v_tag);
    when 'ON_THE_WAY' then
      perform private.push_send(new.customer_id, '🚗 ' || v_name || ' طالع بالطريق',
        'الفني جاي لبيتك هسه.', v_url, v_tag);
    when 'IN_PROGRESS' then
      perform private.push_send(new.customer_id, '🔧 ' || v_name || ' بدأ الشغل',
        'نبلغك من يخلص.', v_url, v_tag);
    when 'COMPLETED' then
      perform private.push_send(new.customer_id, '🎉 خلص الشغل',
        'قيّم ' || v_name || ' بدقيقة، تقييمك يساعد غيرك يختار صح.', v_url, v_tag);
    when 'CANCELLED' then
      if old.provider_id is not null then
        perform private.push_send(old.provider_id, '❌ الطلب انلغى',
          'الزبون ألغى الطلب' || coalesce(': ' || left(new.cancel_reason, 120), '.'), v_url, v_tag);
      end if;
    else
      null;
  end case;
  return new;
exception when others then
  raise warning 'push_request_status failed: %', sqlerrm;
  return new;
end $$;

drop trigger if exists service_requests_push_status on public.service_requests;
create trigger service_requests_push_status
  after update of status on public.service_requests
  for each row execute function public.push_request_status();

-- verification: new request -> admins; decision -> provider
create or replace function public.push_verification() returns trigger
language plpgsql security definer set search_path = public, private as $$
declare
  v_name text;
  a record;
begin
  if tg_op = 'INSERT' then
    if public.is_admin() then
      return new;
    end if;
    select display_name into v_name from public.providers where id = new.provider_id;
    for a in select id from public.users where role = 'admin' and is_active loop
      perform private.push_send(a.id, '🆕 طلب توثيق جديد', coalesce(v_name, 'فني جديد') || ' ينتظر التوثيق',
        '/admin/verifications', 'verify');
    end loop;
  elsif new.status is distinct from old.status then
    if new.status = 'verified' then
      perform private.push_send(new.provider_id, '🎉 تم توثيق حسابك ✅',
        'شغّل «متاح الآن» حتى تبدي توصلك الطلبات.', '/provider', 'verify');
    elsif new.status = 'needs_info' then
      perform private.push_send(new.provider_id, 'ℹ️ نحتاج معلومات إضافية',
        coalesce(left(new.admin_notes, 150), 'افتح التطبيق وشوف المطلوب.'), '/provider/profile', 'verify');
    elsif new.status = 'rejected' then
      perform private.push_send(new.provider_id, '❌ ما انقبل طلب التوثيق',
        coalesce(left(new.admin_notes, 150), 'تگدر تقدّم مرة ثانية.'), '/provider/profile', 'verify');
    end if;
  end if;
  return new;
exception when others then
  raise warning 'push_verification failed: %', sqlerrm;
  return new;
end $$;

drop trigger if exists verification_requests_push on public.verification_requests;
create trigger verification_requests_push
  after insert or update of status on public.verification_requests
  for each row execute function public.push_verification();

-- ---------------------------------------------------------------------
-- Permissions
-- ---------------------------------------------------------------------
revoke execute on function
  public.push_subscribe(text, text, text, text), public.push_unsubscribe(text), public.push_status(),
  public.push_public_key(), public.push_service_config(), public.push_service_init(text, text),
  public.push_new_offer(), public.push_request_status(), public.push_verification(),
  private.push_send(uuid, text, text, text, text)
  from public, anon, authenticated;
grant execute on function
  public.push_subscribe(text, text, text, text), public.push_unsubscribe(text), public.push_status(),
  public.push_public_key()
  to authenticated;
grant execute on function public.push_service_config(), public.push_service_init(text, text) to service_role;
